on: 
  pull_request:
  workflow_dispatch:

name: CI

jobs:
  lib:
    name: Extism runtime lib
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Build
        run: make
      - name: Test
        run: make test
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: libextism-${{ matrix.os }}
          path: |
              ./extism-wamr
              ./libextism-wamr.a
